# Generated by Django 4.1.5 on 2023-08-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(upload_to='girls/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=700, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
