# Generated by Django 4.1.5 on 2023-08-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='photo',
            field=models.ImageField(null=True, upload_to='girls/'),
        ),
    ]
